apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-flask-app-deployment
spec:
  replicas: 3  # Number of pod replicas
  selector:
    matchLabels:
      app: simple-flask-app
  template:
    metadata:
      labels:
        app: simple-flask-app
    spec:
      containers:
      - name: simple-flask-app
        image: simple-flask-app:latest  # Replace with your image name if stored in a registry
        ports:
        - containerPort: 5070
        env:
        - name: FLASK_ENV
          value: "production"
